hasenbanck/egui_wgpu_backend

- src/lib.rs
I inspired from this tweet so i decided to create 3d renderable area without bettween CPU and GPU memory copy.
There are two approach ;
- mark pre allocated texture as egui::TextureId
- replace image that is pointed by TextureId
<blockquote class="twitter-tweet"><p lang="en" dir="ltr">I&#39;ve released version 0.2.0 of egui_winit_ash_vk_mem!<a href="https://t.co/PcrrtpGruE">https://t.co/PcrrtpGruE</a><br>User textures are supported from this version.<br>It is now also possible to draw a scene inside a window.<a href="https://twitter.com/hashtag/gamedev?src=hash&amp;ref_src=twsrc%5Etfw">#gamedev</a> <a href="https://twitter.com/hashtag/rustlang?src=hash&amp;ref_src=twsrc%5Etfw">#rustlang</a> <a href="https://t.co/CxvoGYjIcQ">pic.twitter.com/CxvoGYjIcQ</a></p>&mdash; 折登 いつき …
> Enabling 3d rendering in egui::Image or epaint::Mesh on egui_wgpu_backend

- src/lib.rs
[The wgpu documentation](https://docs.rs/wgpu/0.7.0/wgpu/struct.PrimitiveState.html#structfield.strip_index_format) says that `strip_index_format` 'Should be left `None` for non-strip.', which is the case as we're using `wgpu::PrimitiveTopology::TriangleList`. This fix isn't urgent by any means, but I do get a vulkan validation error because of it:
```
VALIDATION [VUID-VkPipelineInputAssemblyStateCreateInfo-topology-00428 (-1077750125)] : Validation Error: [ VUID-VkPipelineInputAssemblyStateCreateInfo-topology-00428 ] Object 0: handle = 0x560f78422700, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xbfc2d693 | vkCreateGraphicsPipelines() pCreateInfo[0]: topology is VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST and primitiveRestartEnable is VK_TRUE. It is invalid. The Vulkan spec states: If topology …
```
> Set `strip_index_format` to `None`

- Cargo.toml
- src/lib.rs
Basically what the title says.
Change uses of egui::clamp to f32::clamp as the former is deprecated
> Update egui to 0.11

- src/lib.rs
I'm working on [nannou_egui](https://github.com/AlexEne/nannou_egui) and webgpu currently fails in the validation step because msaa samples are hardcoded in `egui_wgpu_backend` to `1` and [nannou](https://github.com/nannou-org/nannou) sets this to `4`. Right now the solution is to change the msaa in nannou to `1`, but that's not ideal.
I feel like there should be a more correct way to do this that doesn't involve enabling MSAA for the UI code (render UI to a texture then copy the texture in the final buffer), but I am not familiar with webgpu but it is a simple change that seems useful for now.
> Add sample count to RenderPass

- Cargo.toml
wgpu 0.9 looks to be mostly just internal improvements and a relicense from MPL v2 to MIT/Apache. Code compiles and appears to run fine.
> Upgrade to wgpu 0.9

- Cargo.toml
- src/lib.rs
- src/shader/egui.wgsl
Updates wgpu dependency to 0.10 and fixes breaking changes in the code.
> Update to wgpu 0.10

- src/shader/egui.wgsl
Not specifying the storage class is tolerated by naga / wgpu but not by Chrome / Tint. Adding the storage class makes the backend work on Chrome when using wgpu in a WebAssembly target.
> Add missing storage class in shader

- CHANGELOG.md
- Cargo.toml
This PR adjusts the version range for the library's wgpu dependency. Because there were no API changes, both wgpu 0.10 and 0.11 can be supported simultaneously!
> Support both wgpu 0.10 and 0.11

- CHANGELOG.md
- README.md
- src/lib.rs
- src/shader/egui.wgsl
Closes #46 
Closes #47 
I have left the `web` feature there, so it wouldn't cause an error on updating, it is just a no-op. However, I can remove it if you wish.
~~Technically this should be able to go out in a patch release.~~ it can't as the removal of the mut can break code if you think of a case hard enough.
> Srgb Fixes and Renderpass Re-use

- CHANGELOG.md
- Cargo.toml
- src/lib.rs
Removed the `epi::TextureAllocator` trait impl, since it seems like a relic from the past. I think it wasn't really used in the past anyhow, since the wgpu backend handles resources differently than for example the glow and glium backends.
`egui::Texture` is now called `egui::FontImage`.
Ping @parasyte @cwfitzgerald @Jengamon.
I don't use egui right now, so it would be great if someone could test this change.
> Update to support egui 0.16

- src/lib.rs
As I explain in #53, this makes the API more flexible when all you have is a TextureView.
Since I'm aware this breaks the public API of the crate, let me know if there's a better way to fix this. I'll gladly fix my changes :smile:
> Make egui_texture_from_wgpu_texture and related methods take &wgpu::TextureView instead

- src/lib.rs
First: thanks for providing the egui backends! With Vulkan everything worked out of the box, but with WASM/WebGL I ran into the issue described here: https://github.com/hasenbanck/egui_wgpu_backend/issues/58
Since at least one other person had the same issue [here](https://github.com/gfx-rs/wgpu/issues/2573), I thought that I might as well push my local fork. In addition to the padding that solves the WebGL issue, I also added size limits in a separate commit.
> Add padding for WebGL support by padding buffer content

- Cargo.toml
- src/lib.rs
- src/shader/egui.wgsl
This is based on the updated shaders in #55, additionally incorporating fixes for wgpu 0.13 and egui 0.18.
I did not implement the new "custom drawing" feature enabled by the new `ClippedPrimitive` type. I think that'll take a bit of thinking for how it should fit with wgpu.
I've tested this change in a medium-sized game project and it appears to work.
> Upgrade to wgpu 0.13 and egui 0.18

- src/shader/egui.wgsl
Without this padding in shader, I will get a validation error with webgl2 wgpu backend.
```
panicked at 'wgpu error: Validation Error
Caused by:
In Device::create_render_pipeline
note: label = `egui_pipeline`
Downlevel flags BUFFER_BINDINGS_NOT_16_BYTE_ALIGNED are required but not supported on the device.
This is not an invalid use of WebGPU: the underlying API or device does not support enough features to be a fully compliant implementation. A subset of the features can still be used. If you are running this program on native and not in a browser and wish to work around this issue, call Adapter::downlevel_properties or Device::downlevel_properties to get a listing of the features the current platform supports.
', /Users/currypseudo/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c54 …
```
> fix: wgsl local uniform padding

- Cargo.toml
Does what it says on the tin — the breaking input API changes in egui don't really matter here
> Update to egui 0.21

- Cargo.toml
Bumped the egui version to 0.23. No changes to source needed. Works well for me on Windows in the egui demo project. Let me know if there's any more tests you'd like to see! <3
> bumped egui version to 0.23

- Cargo.toml
- src/lib.rs
WGPU 0.18.0 makes some minor API changes, but doesn't change anything (semantically) that is used by this crate (as far as I can tell)
> Update WGPU to 0.18.0

- Cargo.toml
egui 0.26 has a bunch of features & improvements we're looking for in our [project](github.com/lockbook/lockbook). An update to wgpu was also required to get my project building because eframe 0.26 depends on a version of web-sys that's incompatible with anything before wgpu 0.19.
> bump egui version to 0.26, wgpu version to 0.19

- Cargo.toml
- src/lib.rs
* bump `egui` to 0.27
* bump `wgpu` to 0.20
Only required change for `wgpu` was to add `PipelineCompilationOptions`, and followed the advice "most users can be set to Default::default()" from [docs](https://docs.rs/wgpu/0.20.0/wgpu/struct.PipelineCompilationOptions.html).
> bump egui to 0.27 and wgpu to 0.20

- Cargo.toml
- src/lib.rs
wgpu v 23.0.0 is out. 
`entry_points are now Optional`
https://github.com/gfx-rs/wgpu/releases/tag/v23.0.0
> Bump wgpu version to 23.0.

- CHANGELOG.md
- Cargo.toml
- src/lib.rs
This upgrades egui/wgpu to the latest versions and version bumps to 0.34 to ready a release.
`wgpu::ImageDataLayout` is now deprecated since it was renamed to  `wgpu::TexelCopyBufferLayout`, so that is fixed in these changes.
> Release 0.34 with egui 0.31 and wgpu 24
